films/api/urls.py
from django.urls import path
from .views import (MovieListView,
                    MovieDetailView, AddNewMovie, AddMovieVotes,
                    MovieSearchView, CommentListView, CommetCreateView
                    )

app_name = "movies"


urlpatterns = [
    path('movies', MovieListView.as_view(), name="movie-list"),
    path('add_new_movie', AddNewMovie.as_view(), name="add-movie"),
    path('movies/<pk>', MovieDetailView.as_view(), name="movie-detail"),
    path('add_movie_votes', AddMovieVotes.as_view(), name='add-movie-votes'),
    path('movie_search', MovieSearchView.as_view(), name='movie-search'),
    path('get_comment', CommentListView.as_view(), name='get-comment'),
    path('create_comment', CommetCreateView.as_view(), name='create-comment')
]

films/urls.py
from django.urls import path
from .views import homeView, moviesView, movieRate, searchView

app_name = 'films'



urlpatterns = [
    path('', homeView, name='home'),
    path('movies', moviesView, name='movies'),
    path('movies/search', searchView, name='search'),
    path('movies/<pk>/rate', movieRate, name='rate')
    
]

questions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView
from .schema import schema

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('api/', include('films.api.urls', namespace='movies')),
    path('graphql/', csrf_exempt(GraphQLView.as_view(
        graphiql=True,
        schema=schema
    )) ),
    # path('graphql/', GraphQLView.as_view(
    #     graphiql=True,
    #     schema=schema
    # ) ),
    path('films/', include('films.urls', namespace='films')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

films/models.py
from django.db import models, transaction
from django.shortcuts import reverse
from django.db.models import IntegerField, Model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

class Movie(models.Model):
    title = models.CharField(max_length=100)
    director = models.CharField(max_length=50)
    poster = models.ImageField(null=True, blank=True)
    production_year = models.IntegerField()
    description = models.TextField(blank=True)

    def __str__(self):
        return "{}- {}".format(self.pk, self.title)

    def get_absolute_url(self):
        return reverse('films:rate', kwargs={
            'pk': self.pk
        })


class Vote(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    value = models.IntegerField(validators=[
        MaxValueValidator(5),
        MinValueValidator(1)
    ])

    def __str__(self):
        return "{} has {} ".format(self.movie.title, self.value)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, null=True)
    text = models.TextField(max_length=200)

    def __str__(self):
        return "({}):  {}".format(self.movie, self.text)

films/forms.py
from django.forms import ModelForm, Form
from .models import Movie, Vote
from django import forms


class MovieModelForm(ModelForm):
    class Meta:
        model = Movie
        fields = ["title", "director",
                  "production_year", "description", "poster"]


class MovieVoteValueForm(ModelForm):
    class Meta:
        model = Vote
        fields = ['value']


CHOICES = (
    ('1', 'one'),
    ('2', 'two')
)


class MovieModelForm2(forms.Form):
    check_field = forms.ChoiceField(
        widget=forms.RadioSelect, choices=CHOICES)
    text_field = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'enter something',
        'id': 'text_field'
    }
    ))

films/api/views.py
from films.models import Movie, Vote, Comment
from django.db.models import Q
from rest_framework.generics import (ListAPIView, RetrieveAPIView,
                                     CreateAPIView, UpdateAPIView, DestroyAPIView
                                     )
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from django.shortcuts import get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponse
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST, HTTP_500_INTERNAL_SERVER_ERROR
from .serializers import MoviesListSerializer, MovieDetailSerializer, CommentListSerializer


class MovieListView(ListAPIView):
    permission_classes = (AllowAny, )
    queryset = Movie.objects.all()
    serializer_class = MoviesListSerializer


class MovieDetailView(RetrieveAPIView):
    permission_classes = (AllowAny, )
    serializer_class = MovieDetailSerializer
    queryset = Movie.objects.all()


class AddNewMovie(APIView):
    def post(self, request, *args, **kwargs):
        submitted_form = request.data.get('formData')
        if(submitted_form):
            title = submitted_form['title']
            director = submitted_form['director']
            year = submitted_form['year']
            description = submitted_form['description']
            movie = Movie.objects.create(
                title=title,
                director=director,
                description=description,
                production_year=year
            )
            return Response(status=HTTP_200_OK)
        else:
            return Response(status=Http404)


class AddMovieVotes(APIView):
    def post(self, request, *args, **kwargs):
        title = request.data.get('title')
        value = request.data.get('value')
        movie = Movie.objects.get(title=title)
        vote = Vote.objects.create(movie=movie, value=value)
        vote.save()
        return Response(status=HTTP_200_OK)


class MovieSearchView(APIView):
    def post(self,  request, *args, **kwargs):
        queryset = Movie.objects.all()
        query = request.data.get('searchInput')
        arr = []
        if query and len(query) > 1:
            queryset = queryset.filter(
                Q(title__icontains=query)
            ).distinct()
            for i in range(len(queryset)):
                name = queryset[i].title
                id = queryset[i].id
                dic = dict(movie_id=id, movie_title=name)
                arr.append(dic)
        if arr:
            return Response(data=arr, status=HTTP_200_OK)
        else:
            return Response(status=HTTP_400_BAD_REQUEST)


class CommentListView(ListAPIView):
    permission_classes = [IsAuthenticated, ]
    serializer_class = CommentListSerializer

    def get_queryset(self):
        try:
            comments = Comment.objects.all()
            return comments
            
        except ObjectDoesNotExist:
            return Response(status=HTTP_400_BAD_REQUEST)


class CommetCreateView(APIView):
    def post(self, request, *args, **kwargs):
        movie_id = self.request.data['movie_id']
        movie_comment = self.request.data['movie_comment']
        if movie_id and movie_comment:
            comments = Comment.objects.create(
                user=self.request.user,
                text=movie_comment,
                movie_id=movie_id
            )
            comments.save()
            return Response(data='done', status=HTTP_200_OK)
        else:
            return Response(data="some field is missing", status=HTTP_400_BAD_REQUEST)

films/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.views.generic import ListView
from django.shortcuts import get_object_or_404
from .models import Movie, Vote
from .forms import (
    MovieModelForm, MovieVoteValueForm, MovieModelForm2
)


def homeView(request):
    movies = Movie.objects.all()
    vote = Vote.objects.all()
    if request.method == "POST":
        form = MovieModelForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = MovieModelForm()
    context = {
        'movies': movies,
        'form': form,
    }
    return render(request, "home.html", context)

def searchView(request):
    queryset = Movie.objects.all()
    query = request.POST.get('q')
    context = {}
    if query and len(query) > 1:
        queryset = queryset.filter(
            Q(title__icontains=query)
        ).distinct()
        context['queryset'] = queryset
    return render(request, 'search_results.html', context)

def moviesView(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies
    }
    return render(request, 'movies.html', context)



def movieRate(request, pk):
    movie = Movie.objects.get(pk=pk)
    movies_with_same_director = Movie.objects.filter(director=movie.director).exclude(title=movie.title)
    if request.method == "POST":
        vote_value = request.POST['customRadioInline']
        new_vote = Vote.objects.create(movie=movie, value=vote_value)
        new_vote.save()
        movie.save()
    context = {
        'movie': movie,
        'similar': movies_with_same_director,
    }
    movie_votes = Vote.objects.filter(movie=movie) 
    if movie_votes.exists():
        movies_counts = movie_votes.count() * 5
        movie_votes_values = 0
        for x in range(len(movie_votes)):
            movie_votes_values += movie_votes[x].value
        votes = round(movie_votes_values/movies_counts * 5, 2)
        context['votes'] = votes
    
    return render(request, 'rate.html', context)

films/templates/answers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  <div>
      <div style="flex-direction: row; padding: 5rem; color: aliceblue; background-color: black;">
        {% for ans in question.answers_set.all %}
            <h2>{{ans}}</h2>
            <hr>
        {%endfor%}
      </div>
     
  </div>
</body>
</html>

films/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Mov</title>
</head>
{% include 'navbar.html'%}

<body>
    {% block content %}
    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

films/templates/home.html
{% extends 'base.html'%}
{% load widget_tweaks %}

{% block content %}

<main>
    <div class="container">
        <div class="row" style="padding: 4rem">
            <div class="col border" style="padding: 1rem; margin-right: 5rem;">
                    {% for film in movies.all %}
                    <a href="{{ film.get_absolute_url }}">
                        <h2>{{film.title}}</h2>
                    </a>
                    <h5>{{film.director}}</h5>
                    <h5 class="hoverable">{{film.production_year}}</h5>
                    <hr>
                    {%endfor%}
            </div>
            <div class="col px-3 ml-2 bg-dark h-100 py-2 text-light" style="border-radius: 10px;">
                <h2 class=" text-light text-center ">Add Movies</h2>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="movie_title">Movie Title</label>
                        {% render_field form.title class="form-control col=3"%}
                    </div>
                    <div class="form-group">
                        <label for="movie_director">Director</label>
                        {% render_field form.director class="form-control" col=3  %}
                    </div>
                    <div class="form-group">
                        <label for="movie_year">Production Year</label>
                        {% render_field form.production_year class="form-control" col=2 %}

                    </div>
                    <div class="form-group">
                        <label for="movie_description">Description</label>
                        {% render_field form.description class="form-control" col=3%}

                    </div>
                    <!-- <input type="file" class="form-control-file" id="exampleFormControlFile1"> -->
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>

    </div>
</main>
{% endblock %}

films/templates/movies.html
{% extends 'base.html' %}
{% block content %}
<body>
    <div class="container align-content-center align-items-center"style="padding: 4rem; margin-right: 12rem;">
        <div class="row justify-content-center">
                {% for movie in movies %}
            <div class="card col-3 mb-2">
                {% if movie.poster %}
                    <img src='{{ movie.poster.url }}' class="card-img" style="width:fit-content; height: 14rem;">
                {% endif %}
                <div class="card-body">
                    <a href="{{movie.get_absolute_url}}"><h3 class="card-title">{{movie.title}}</h3></a>
                    <h6 class="card-title">Directed by: <b>{{movie.director}}</b></h6>
                    <p class="card-text">{{movie.description}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
{% endblock %}

<!-- style="width: 15rem; height: auto; margin-left: 3px;" -->

films/templates/navbar.html
<div>
  <nav class="navbar navbar-expand-lg navbar-dark badge-dark py-3 px-5">
    <a class="navbar-brand" href="{% url 'films:home' %}">Home</a>
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'films:movies' %}">All Movies</a>
      <a class="nav-item nav-link" href="#">Directors</a>
      <a class="nav-item nav-link" href="#">Series</a>
    </div>
    <div class=" align-content-center" style="margin-left: 60%;" >
      <form action="{% url 'films:search' %}" method="POST">
        {% csrf_token %}
        <div class="form-group " class="search-form">
        <input style= "border-radius: 10px; " class="px-2 py-1 text-center hoverabl" type="text" name="q" placeholder="search for a movie">
        </div>
      </form>
    </div>
  </nav>

</div>

films/templates/rate.html
{% extends 'base.html' %}
{% block content %}

<body>
    <div class="row">
        <div class="col container m-5 px-4 py-2" ">
            <div class=" card w-50">
            {% if movie.poster %}
            <img src='{{ movie.poster.url }}' class="card-img">
            {% endif %}

            <div class="card-body">
                <h3 class="card-title">{{movie.title}}</h3>
                <h6 class="card-title">Directed by: <b>{{movie.director}}</b></h6>

                <h6>Movie ratings: {{votes}}</h6>
                <p class="card-text">{{movie.description}}</p>
                <hr>
                <h5>Vote below</h5>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <div>
                            <div class="custom-control custom-radio custom-control-inline">
                                <input type="radio" id="customRadioInline1" name="customRadioInline"
                                 class="custom-control-input" value=1>
                                <label class="custom-control-label" for="customRadioInline1">1</label>
                            </div>

                            <div class="custom-control custom-radio custom-control-inline">
                                 <input type="radio" id="customRadioInline2" name="customRadioInline"
                                     class="custom-control-input" value=2>
                                <label class="custom-control-label" for="customRadioInline2">2</label>
                            </div>

                            <div class="custom-control custom-radio custom-control-inline">
                                <input type="radio" id="customRadioInline3" name="customRadioInline"
                                    class="custom-control-input" value=3>
                                <label class="custom-control-label" for="customRadioInline3">3</label>
                            </div>
                            <div class="custom-control custom-radio custom-control-inline">
                                <input type="radio" id="customRadioInline4" name="customRadioInline"
                                    class="custom-control-input" value=4>
                                <label class="custom-control-label" for="customRadioInline4">4</label>
                            </div>
                            <div class="custom-control custom-radio custom-control-inline">
                                <input type="radio" id="customRadioInline5" name="customRadioInline"
                                    class="custom-control-input" value=5>
                                <label class="custom-control-label" for="customRadioInline5">5</label>
                            </div>
                        </div>

                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
               
            </div>
        </div>
    </div>
    <div class="col container m-5 py-2">
        <div class="list-group">
            <h2 class="mb-4">Similar Movies</h2>

            {% for mov in similar %}
            <a href="{{mov.get_absolute_url}}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{mov.title}}</h5>
                    <small>{{movie.director}}</small>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
    </div>
</body>
{% endblock %}

films/templates/search_results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div style="margin-left: 40%; margin-top: 10%;">
    {% if queryset %}
    <div style="align-items: center;">
        <h2 class="my-2">Results of your search</h2>
        <br><br>
        <div class="card" style="width: 18rem; align-items: center;">
            <ul class="list-group list-group-flush">
                {% for movie in queryset %}
                <li class="list-group-item"><a href="{{ movie.get_absolute_url }}">
                        <h2>{{ movie.title }}</h2>
                    </a></li>
                {% endfor %}
            </ul>
        </div>
    </div>


    {% else %}
    <h3 class="">No results found </h3>

    {% endif %}
</div>
{% endblock %}